name: 'ci'
on:
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: [21, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Run unit tests
        run: pnpm run test:unit

  ssr-sfc-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: [21, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Run SSR tests
        run: pnpm run test:ssr

      - name: Run compiler-sfc tests
        run: pnpm run test:sfc

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        node: [21, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Run e2e tests
        run: pnpm run test:e2e

      - name: Run transition tests
        run: pnpm run test:transition

  type-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node: [21, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Run srouce type check
        run: pnpm run ts-check

      - name: Run type declaration tests
        run: pnpm run test:types

  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - run: pnpm install

      - name: Build dist files
        run: pnpm run build

      - name: Copy LICENSE into vue-template-compiler package
        run: cp LICENSE packages/template-compiler/LICENSE

      - name: Pack vue-template-compiler
        run: npm pack
        working-directory: packages/template-compiler

      - name: Upload vue-template-compiler tarball
        uses: actions/upload-artifact@v4
        with:
          name: vue-template-compiler-tarball
          path: packages/template-compiler/vue-template-compiler-*.tgz
          if-no-files-found: error
